import React, { useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Shield, ChevronRight, Menu, X } from 'lucide-react';
import Logo from './Logo';

const documents = {
  'privacy': {
    title: 'Privacy Policy',
    lastUpdated: 'August 15, 2026',
    content: (
      <>
        <p>At Cyber Sentinel, we take your privacy and data security incredibly seriously. This Privacy Policy details how we collect, process, and protect your information when you use our zero-trust platform.</p>
        
        <h3 className="text-xl font-bold text-white mt-8 mb-4">1. Information We Collect</h3>
        <p>We only collect the absolute minimum information required to deliver our enterprise services. This includes:</p>
        <ul className="list-disc pl-6 space-y-2 mt-4">
          <li><strong>Account Information:</strong> Name, work email address, and billing details provided during registration.</li>
          <li><strong>Telemetry Data:</strong> Anonymized performance metrics from our AI agents to improve diagnostic accuracy.</li>
          <li><strong>Security Logs:</strong> Encrypted audit trails generated by our zero-trust architecture.</li>
        </ul>

        <h3 className="text-xl font-bold text-white mt-8 mb-4">2. How We Use Your Information</h3>
        <p>Your data is used exclusively for providing and improving our services. We do not, and will never, sell your enterprise data to third parties. Our AI models are trained on isolated, generalized datasets and do not ingest your proprietary information without explicit consent.</p>

        <h3 className="text-xl font-bold text-white mt-8 mb-4">3. Data Residency & Encryption</h3>
        <p>All data at rest is encrypted using AES-256-GCM. Data in transit is secured via TLS 1.3. You have full control over data residency regions (US-East, EU-Central, APAC-South) to comply with local regulations.</p>
      </>
    )
  },
  'terms': {
    title: 'Terms of Service',
    lastUpdated: 'September 1, 2026',
    content: (
      <>
        <p>These Terms of Service govern your use of the Cyber Sentinel enterprise platform and associated services.</p>
        
        <h3 className="text-xl font-bold text-white mt-8 mb-4">1. Enterprise Licensing</h3>
        <p>Cyber Sentinel provides non-exclusive, non-transferable licenses to use our software for internal business operations. Reverse engineering, decompiling, or attempting to extract source code from our AI models or zero-trust clients is strictly prohibited.</p>

        <h3 className="text-xl font-bold text-white mt-8 mb-4">2. Service Level Agreement (SLA)</h3>
        <p>We guarantee 99.999% uptime for our core routing and authentication infrastructure. Scheduled maintenance windows will be communicated at least 14 days in advance. Remedies for SLA breaches are detailed in your specific Enterprise Contract.</p>
      </>
    )
  },
  'cookies': {
    title: 'Cookie Policy',
    lastUpdated: 'July 10, 2026',
    content: (
      <>
        <p>We use essential cookies to ensure the secure operation of our zero-trust authentication layer. We do not use third-party tracking cookies.</p>
        
        <h3 className="text-xl font-bold text-white mt-8 mb-4">1. Essential Cookies</h3>
        <p>These cookies are required for platform security, including session management, CSRF token validation, and multi-factor authentication states. They cannot be disabled.</p>

        <h3 className="text-xl font-bold text-white mt-8 mb-4">2. Performance Cookies</h3>
        <p>We use highly anonymized, first-party cookies to measure latency across our global Edge network. You may opt out of these in your organizational dashboard.</p>
      </>
    )
  },
  'security': {
    title: 'Security Whitepaper',
    lastUpdated: 'October 5, 2026',
    content: (
      <>
        <div className="bg-slate-900 border border-slate-700 p-6 rounded-xl flex flex-col items-center justify-center text-center py-16">
          <Shield className="text-cyan-500 mb-4" size={48} />
          <h3 className="text-2xl font-bold text-white mb-2">Restricted Access</h3>
          <p className="text-slate-400 max-w-md mx-auto mb-6">Our comprehensive Security Architecture Whitepaper contains proprietary infrastructure details and is available under NDA only.</p>
          <Link to="/#contact" className="bg-white text-slate-950 px-6 py-3 rounded-lg font-bold hover:bg-slate-200 transition-colors">
            Contact Engineering
          </Link>
        </div>
      </>
    )
  },
  'soc2': {
    title: 'SOC2 Compliance Status',
    lastUpdated: 'January 1, 2026',
    content: (
      <>
        <div className="bg-slate-900 border border-slate-700 p-6 rounded-xl flex flex-col items-center justify-center text-center py-16">
          <Shield className="text-green-500 mb-4" size={48} />
          <h3 className="text-2xl font-bold text-white mb-2">SOC2 Type II Certified</h3>
          <p className="text-slate-400 max-w-md mx-auto mb-6">Cyber Sentinel maintains active SOC2 Type II compliance. The full auditor's report is available to enterprise customers and prospects under NDA.</p>
          <Link to="/#contact" className="bg-white text-slate-950 px-6 py-3 rounded-lg font-bold hover:bg-slate-200 transition-colors">
            Request Auditor Report
          </Link>
        </div>
      </>
    )
  }
};

function LegalPage() {
  const { documentId } = useParams();
  const [isMobileMenuOpen, setIsMobileMenuOpen] = React.useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [documentId]);

  const doc = documents[documentId] || {
    title: 'Document Not Found',
    lastUpdated: '',
    content: <p>The requested legal document could not be found.</p>
  };

  return (
    <div className="min-h-screen bg-[#020610] text-slate-300 font-sans selection:bg-cyan-500/30">
      {/* Navigation */}
      <nav className="fixed w-full z-50 bg-[#020610]/80 backdrop-blur-xl border-b border-slate-800/80">
        <div className="max-w-[92%] mx-auto px-4 lg:px-8 py-5">
          <div className="flex justify-between items-center">
            <Link to="/" className="flex items-center gap-3 group">
              <Logo className="w-9 h-9 text-white group-hover:text-slate-300 transition-colors" />
              <span className="text-xl font-bold tracking-tight text-white group-hover:text-slate-200 transition-colors">Cyber Sentinel</span>
            </Link>
            
            <div className="hidden md:flex items-center gap-8 text-sm font-medium">
              <Link to="/#home" className="hover:text-white transition-all hover:scale-105 transform inline-block">Home</Link>
              <Link to="/#about" className="hover:text-white transition-all hover:scale-105 transform inline-block">About Us</Link>
              <Link to="/#solutions" className="hover:text-white transition-all hover:scale-105 transform inline-block">Solutions</Link>
              <Link to="/#contact" className="hidden md:block bg-white text-slate-950 px-5 py-2 rounded-lg text-sm font-bold hover:bg-slate-200 transition-all hover:scale-105 transform shadow-[0_0_20px_rgba(255,255,255,0.1)]">
                Initiate Secure Comms
              </Link>
            </div>

            <button className="md:hidden text-white p-2" onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}>
              {isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {isMobileMenuOpen && (
          <div className="md:hidden absolute top-full left-0 w-full bg-[#050b14] border-b border-slate-800 p-6 flex flex-col gap-6 shadow-2xl">
            <Link to="/#home" onClick={() => setIsMobileMenuOpen(false)} className="hover:text-white transition-colors">Home</Link>
            <Link to="/#about" onClick={() => setIsMobileMenuOpen(false)} className="hover:text-white transition-colors">About Us</Link>
            <Link to="/#solutions" onClick={() => setIsMobileMenuOpen(false)} className="hover:text-white transition-colors">Solutions</Link>
            <Link to="/#contact" onClick={() => setIsMobileMenuOpen(false)} className="bg-white text-slate-950 px-5 py-3 rounded-lg font-bold text-center mt-4 text-sm">
              Initiate Secure Comms
            </Link>
          </div>
        )}
      </nav>

      {/* Main Content */}
      <main className="pt-32 pb-24">
        <div className="max-w-3xl mx-auto px-4 lg:px-8">
          <div className="mb-12">
            <div className="flex items-center gap-2 text-sm text-cyan-400 font-bold tracking-widest uppercase mb-4">
              <Link to="/" className="hover:text-cyan-300 transition-colors">Home</Link>
              <ChevronRight size={16} />
              <span>Legal</span>
            </div>
            <h1 className="text-4xl md:text-6xl font-extrabold text-white tracking-tight mb-4">{doc.title}</h1>
            {doc.lastUpdated && (
              <p className="text-slate-400 font-medium">Last Updated: {doc.lastUpdated}</p>
            )}
          </div>
          
          <div className="prose prose-invert prose-slate max-w-none prose-p:text-slate-300 prose-p:leading-relaxed prose-headings:tracking-tight prose-a:text-cyan-400 hover:prose-a:text-cyan-300">
            {doc.content}
          </div>
        </div>
      </main>

      {/* Simplified Footer */}
      <footer className="bg-[#020610] pt-16 pb-8 border-t border-slate-800/80">
        <div className="max-w-[92%] mx-auto px-4 lg:px-8 flex flex-col md:flex-row justify-between items-center gap-4 text-slate-600 text-sm">
          <p>© 2026 Cyber Sentinel Inc. All rights reserved.</p>
          <div className="flex items-center gap-6">
            <Link to="/legal/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link to="/legal/terms" className="hover:text-white transition-colors">Terms</Link>
            <Link to="/legal/security" className="hover:text-white transition-colors">Security</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default LegalPage;
